
package view;

import conexao.funcBD;
import model.CadastroFunc;
import model.CadastroFunc;
import model.CadastroFuncTableModel;
import model.CadastroFuncTableModel;


public class ViewCadastroFunc extends javax.swing.JFrame {

   CadastroFuncTableModel TableModel = new CadastroFuncTableModel();
           
           
    public ViewCadastroFunc() {
        initComponents();
        
        jTCadastroFunc.setModel(TableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTCadastroFunc = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNasc = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTCadastroFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTCadastroFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCadastroFuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCadastroFunc);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Email:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Endereco:");

        jLabel6.setText("Nascimento:");

        jLabel7.setText("Cargo:");

        jLabel8.setText("Salario:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("CADASTRO FUNCIONARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(jButton4)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(3, 3, 3)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTel)
                            .addComponent(txtEmail)
                            .addComponent(txtCpf)
                            .addComponent(txtNome)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastroFunc f = new CadastroFunc();
        
        f.setNome(txtNome.getText());
        f.setCpf(txtCpf.getText());
        f.setEmail(txtEmail.getText());
        f.setTelefone(txtTel.getText());
        f.setEndereco(txtEndereco.getText());
        f.setNascimento(txtNasc.getText());
        f.setCargo(txtCargo.getText());
        f.setSalario(txtSalario.getText());
        
        funcBD.insertFunc(f);
        TableModel.addRow(f);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      txtNome.setText(null);
      txtCpf.setText(null);
      txtEmail.setText(null);
      txtTel.setText(null);
      txtEndereco.setText(null);
      txtNasc.setText(null);
      txtCargo.setText(null);
      txtSalario.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTCadastroFunc.getSelectedRow()!= -1){
            CadastroFunc f = new CadastroFunc();
            
            f.setCpf((String)jTCadastroFunc.getValueAt(jTCadastroFunc.getSelectedRow(),1));
            
            funcBD.DeleteFunc(f);
            
            TableModel.removeRow(jTCadastroFunc.getSelectedRow());
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTCadastroFunc.getSelectedRow() != -1){
            
                try {

                String novoNome = txtNome.getText();
                String novoCPF = txtCpf.getText();
                String novoEmail = txtEmail.getText();
                String novoTelefone = txtTel.getText();
                String novoEndereco = txtEndereco.getText();
                String novoNasc = txtNasc.getText();
                String novoCargo = txtCargo.getText();
                String novoSalario = txtSalario.getText();

                // Atualizar a tabela de acordo com a interface gráfica
                TableModel.setValueAt(novoNome, jTCadastroFunc.getSelectedRow(), 0);
                TableModel.setValueAt(novoCPF, jTCadastroFunc.getSelectedRow(), 1);
                TableModel.setValueAt(novoEmail, jTCadastroFunc.getSelectedRow(), 2);
                TableModel.setValueAt(novoTelefone, jTCadastroFunc.getSelectedRow(), 3);
                TableModel.setValueAt(novoEndereco, jTCadastroFunc.getSelectedRow(), 4);
                TableModel.setValueAt(novoNasc, jTCadastroFunc.getSelectedRow(), 5);
                TableModel.setValueAt(novoCargo, jTCadastroFunc.getSelectedRow(), 6);
                TableModel.setValueAt(novoSalario, jTCadastroFunc.getSelectedRow(), 7);

                // Criar um objeto Cliente com os novos dados
                CadastroFunc funcatt = new CadastroFunc();
                funcatt.setNome(novoNome);
                funcatt.setCpf(novoCPF);
                funcatt.setEmail(novoEmail);
                funcatt.setTelefone(novoTelefone);
                funcatt.setEndereco(novoEndereco);
                funcatt.setNascimento(novoNasc);
                funcatt.setCargo(novoCargo);
                funcatt.setSalario(novoSalario);

                // Criar uma instância de ClienteBD
                funcBD funcBD = new funcBD();

                // Chamar o método de atualização no banco de dados
                funcBD.updateFunc(funcatt);

                System.out.println("Atualizado no banco de dados!");

            } catch (Exception ex) {
                ex.printStackTrace();
                // Lide com exceções de maneira apropriada
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
            
            CadastroFuncTableModel tblModel = (CadastroFuncTableModel)jTCadastroFunc.getModel();

            String tblNome = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 0);
            String tblCPF = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 1);
            String tblEmail = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 2);
            String tblTelefone = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 3);
            String tblEndereco = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 4);
            String tblNasc = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 5);
            String tblCargo = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 6);
            String tblSalario = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 7);
            
            
            txtNome.setText(tblNome);
            txtCpf.setText(tblCPF);
            txtEmail.setText(tblEmail);
            txtTel.setText(tblTelefone);
            txtEndereco.setText(tblEndereco);
            txtNasc.setText(tblNasc);
            txtCargo.setText(tblCargo);
            txtSalario.setText(tblSalario); 
    }//GEN-LAST:event_formMouseClicked

    private void jTCadastroFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCadastroFuncMouseClicked
                   
            CadastroFuncTableModel tblModel = (CadastroFuncTableModel)jTCadastroFunc.getModel();

            String tblNome = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 0);
            String tblCPF = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 1);
            String tblEmail = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 2);
            String tblTelefone = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 3);
            String tblEndereco = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 4);
            String tblNasc = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 5);
            String tblCargo = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 6);
            String tblSalario = (String) tblModel.getValueAt(jTCadastroFunc.getSelectedRow(), 7);
            
            
            txtNome.setText(tblNome);
            txtCpf.setText(tblCPF);
            txtEmail.setText(tblEmail);
            txtTel.setText(tblTelefone);
            txtEndereco.setText(tblEndereco);
            txtNasc.setText(tblNasc);
            txtCargo.setText(tblCargo);
            txtSalario.setText(tblSalario); 
    }//GEN-LAST:event_jTCadastroFuncMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCadastroFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCadastroFunc;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
